# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 03:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso_code', models.CharField(max_length=4)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateField(default=datetime.datetime.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_currency', to='api.Currency')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_currency', to='api.Currency')),
            ],
        ),
    ]
