# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='iso_code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
