# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 04:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20151220_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
